# Seed Dispenser configuration (allow dispensers to place seeds on farmland)
seed-dispenser:
  enabled: true

# Land Claims configuration
land-claims:
  enabled: true
  # How many claims each player can have.
  # More than 1 is recommended in case a player wants to claim a shape that isn't rectangular
  max-claims: 30
  # How large a single claim can be.
  # Make sure to consider vertical and horizontal sizes.
  max-claim-size: 50000

# Entity Claiming configuration
entity-claims:
  enabled: true
  # How many entities a player can claim.
  max-claims: 1000

# Silk Touch Spawners configuration
silk-spawners:
  enabled: true

# What level of console logging to do.
# This is mainly so when I forget to commit info logs, it doesn't spam console
# Must be one of 'error', 'warn', 'info', or 'debug'
log-level: warn

# /hat
slash-hat: true

# nicknames
nicknames: true
# name colors
name-colors: true

teleportation:
  # How long you stay in place before teleporting, in seconds
  timer: 5
  # How long you wait between teleports, in seconds
  cooldown: 10
  homes:
    enabled: true
  tpa:
    enabled: true
  warp:
    enabled: true
  back:
    enabled: true
  spawn:
    enabled: true

graves:
  enabled: true

zombify:
  enabled: true
  
filters:
  brainrot:
    enabled: false
    regex: ":shushing_face: :deaf_man:, :shushing_face::deaf_man:, *461n 9055*, *4d1n r0ss*, *5c1b1di*, *5k1b1dy*, *a6in ross*, *adin ross*, *admin ross*, *baby gronk*, *bb gr0nk*, *bb gronk*, *BOMBARDINO CROCODILO*, *bopboompow*, *f4num*, *fanum*, *fire in the hole*, *g00n1ng*, *g00ning*, *g74tt*, *gedagedi*, *gooning*, *gy4tt*, *gyatt*, *hawk 2*, *hawk tua*, *hawk tuah*, *hawk two*, *kai cenat*, *low taper fade*, *m3w*, *m4xx1ng*, *m4xxing*, *maxx1ng*, maxxing, *mewer*, *mewing*, *quandale dingle*, *r177*, *r1zz*, rizz, *sc1b1d1*, *sc1b1dy*, *scibidi*, *scibidy*, *sigma*, *six*seven*, *sk1b1*, *sk1bi*, *skbidi*, *skibi*, *skibiddi*, *skibide*, *skibidi*, *skibidy*, *skibity*, *skybidi*, *tralalero*, tuah, *tung*, *tung sahur*, *unohio*, *water on the hill*"
    message: "Please take your brainrot somewhere else."
  slur:
    enabled: true
    fetch:
      enabled: true
      link: "https://extras.km7dev.me/slurFilter"
    message: "Slurs aren't allowed on this server, please don't attempt to type them."

no-explosions:
  enabled: false

potion-filter:
  enabled: false

not-too-expensive:
  enabled: true